package com.morrowshop.controller;
import com.morrowshop.domain.Product;import com.morrowshop.service.ProductService;import com.morrowshop.service.impl.ProductServiceImpl;import java.io.IOException;import java.math.BigDecimal;import javax.servlet.*;import javax.servlet.annotation.WebServlet;import javax.servlet.http.*;
@WebServlet(name="adminProductController",urlPatterns={"/admin/products","/admin/product"})
public class AdminProductController extends HttpServlet{
 private final ProductService service=new ProductServiceImpl();
 protected void doGet(HttpServletRequest req,HttpServletResponse res)throws ServletException,IOException{if(req.getServletPath().equals("/admin/product")){String raw=req.getParameter("id");if(raw!=null&&!raw.isEmpty())try{Product p=service.getAdmin(Long.parseLong(raw));if(p==null){res.sendError(404);return;}req.setAttribute("product",p);}catch(NumberFormatException e){res.sendError(400);return;}req.getRequestDispatcher("/WEB-INF/views/admin/product-form.jsp").forward(req,res);}else{req.setAttribute("products",service.getAllAdmin());req.getRequestDispatcher("/WEB-INF/views/admin/products.jsp").forward(req,res);}}
 protected void doPost(HttpServletRequest req,HttpServletResponse res)throws ServletException,IOException{String action=req.getParameter("action");try{if("delete".equals(action)){service.delete(Long.parseLong(req.getParameter("id")));}else{Product p=read(req);service.save(p);}res.sendRedirect(req.getContextPath()+"/admin/products");}catch(IllegalArgumentException e){res.setStatus(400);req.setAttribute("error",e.getMessage());req.setAttribute("product",readSafely(req));req.getRequestDispatcher("/WEB-INF/views/admin/product-form.jsp").forward(req,res);}catch(RuntimeException e){getServletContext().log("Admin product operation failed",e);res.sendError(500);}}
 private Product read(HttpServletRequest r){Product p=new Product();String id=r.getParameter("id");if(id!=null&&!id.isEmpty())p.setId(Long.valueOf(id));p.setSku(required(r,"sku",40));p.setName(required(r,"name",120));p.setDescription(required(r,"description",5000));p.setCategory(required(r,"category",50));p.setImageUrl(required(r,"imageUrl",500));try{p.setPrice(new BigDecimal(r.getParameter("price")));p.setStock(Integer.parseInt(r.getParameter("stock")));}catch(Exception e){throw new IllegalArgumentException("가격과 재고를 올바르게 입력해 주세요.");}if(p.getPrice().signum()<0||p.getStock()<0)throw new IllegalArgumentException("가격과 재고는 0 이상이어야 합니다.");p.setFeatured("true".equals(r.getParameter("featured")));p.setActive(true);return p;}
 private Product readSafely(HttpServletRequest r){try{return read(r);}catch(Exception e){return new Product();}}
 private String required(HttpServletRequest r,String n,int max){String v=r.getParameter(n);if(v==null||v.trim().isEmpty()||v.trim().length()>max)throw new IllegalArgumentException("필수 항목과 입력 길이를 확인해 주세요.");return v.trim();}
}
