<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html><html lang="ko"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>마이페이지 | Morrow</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/shop.css"><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/auth.css"><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/profile.css"></head>
<body><header class="site-header"><a class="brand" href="${pageContext.request.contextPath}/">Morrow<span>.</span></a><nav aria-label="주요 메뉴"><a href="${pageContext.request.contextPath}/products">Shop</a><a href="${pageContext.request.contextPath}/account/orders">Orders</a></nav><form method="post" action="${pageContext.request.contextPath}/logout" class="logout-form"><input type="hidden" name="csrfToken" value="<c:out value='${sessionScope.csrfToken}'/>"><button type="submit">로그아웃</button></form></header>
<main class="profile-page"><section class="profile-hero"><div><p class="eyebrow">My account</p><h1><c:out value="${sessionScope.loginUser.name}"/>님,<br>반가워요.</h1><p class="profile-lead">계정 정보와 쇼핑 활동을 한곳에서 확인하세요.</p></div><dl class="profile-info" aria-label="회원 정보"><div><dt>이메일</dt><dd><c:out value="${sessionScope.loginUser.email}"/></dd></div><div><dt>회원 유형</dt><dd><c:out value="${sessionScope.loginUser.role}"/></dd></div></dl></section>
<section class="account-actions" aria-labelledby="account-menu-title"><div class="section-heading account-heading"><div><p class="eyebrow">Quick menu</p><h2 id="account-menu-title">나의 쇼핑</h2></div></div><div class="account-grid">
<a class="account-card" href="${pageContext.request.contextPath}/account/cart"><span class="account-card__number">01</span><h3>장바구니</h3><p>담아 둔 상품과 수량을 확인하고 주문을 진행해요.</p><b>확인하기 →</b></a>
<a class="account-card" href="${pageContext.request.contextPath}/account/orders"><span class="account-card__number">02</span><h3>주문 내역</h3><p>지금까지 완료한 주문과 결제 금액을 확인해요.</p><b>확인하기 →</b></a>
<a class="account-card" href="${pageContext.request.contextPath}/products"><span class="account-card__number">03</span><h3>쇼핑 계속하기</h3><p>Morrow가 고른 새로운 상품을 둘러보세요.</p><b>둘러보기 →</b></a>
<c:if test="${sessionScope.loginUser.admin}"><a class="account-card account-card--accent" href="${pageContext.request.contextPath}/admin/products"><span class="account-card__number">Admin</span><h3>상품 관리</h3><p>상품을 등록하고 재고 및 노출 상태를 관리해요.</p><b>관리하기 →</b></a></c:if>
</div></section></main></body></html>
